### ISSUE TITLE
Force Dropbox ReAuth for OAuth2?

### ISSUE THREAD

**Issue by ablearcher9** [dropbox/dropbox-sdk-ruby#25]
Is there a way to force Dropbox to present the user with a login screen when trying to authorize an app via Oauth2 even if they are already authenticated on Dropbox.com?

Use case: Our app allows users to integrate with multiple Dropbox accounts, and after the first authorization, they will be logged in. We can use the force_reapprove flag, but ideally we'd want the user to always be presented with a login screen.

**Comment by varenc** [comment]
this is a bit outside of the scope of the ruby SDK since you're asking about the general OAuth page.  There's no officially documented way to force a logout right now.  It should be straightforward for you users to click the logout button on that screen though... I suppose you could try redirect them to http://www.dropbox.com/logout but I can't condone that as the official way to do this.

**Comment by seanstory** [comment]
It seems that the query param `force_reapprove=true` might do the trick.
https://github.com/dropbox/dropbox-sdk-java/blob/master/src/main/java/com/dropbox/core/DbxWebAuth.java#L281
